bol:
  outputs:
    dev:
      dataset: bolcom_case
      fixed_retries: 1
      keyfile: C:\Users\kashi\OneDrive\Documents\bol.com\fluted-oath-218410-eabe223009d9.json
      location: US
      method: service-account
      priority: interactive
      project: fluted-oath-218410
      threads: 2
      timeout_seconds: 300
      type: bigquery
  target: dev
